### ISSUE TITLE
FYI: Got This Warning When Compiling

### ISSUE THREAD

**Issue by chuckmoore55** [kyllingstad/zmqd#19]
Hi,

Just to let you know, this popped up:
Error	1	Deprecation: module std.c.windows.winsock is deprecated - Import core.sys.windows.winsock2 instead	C:\D\zmqd-master\src\zmqd.d	94	

On my local system/solution, I replaced the deprecated module with the suggested one and indeed the the message went away.

Chuck

**Comment by kyllingstad** [comment]
Thanks for the heads-up! Fixed now: bc6a12f96a8fcc7e4b6b66d080e01c46aedba991
