### ISSUE TITLE
Should we handle EINTR the same as EAGAIN?

### ISSUE THREAD

**Issue by Panke** [kyllingstad/zmqd#26]
I am currently converting all missing examples from the ZGuide to D and I am currently working on https://zguide.zeromq.org/docs/chapter2/#Handling-Interrupt-Signals.

While working on this, I have come to the conclusion that EINTR should be handled the same as EAGAIN. What do you think?

**Comment by Panke** [comment]
@kyllingstad

**Comment by kyllingstad** [comment]
Sorry for the (very) late reply. I think you are right, handling them in the same way seems sensible. If you make a pull request, I'd be happy to accept it.

**Comment by Panke** [comment]
No problem! I am glad that you are back :-)

**Comment by kyllingstad** [comment]
Closed by #30.
